#!/bin/bash

protected_branches="master test"

branch="$(git rev-parse --abbrev-ref HEAD)"

for protected_branch in $protected_branches; do
  if [ "$branch" = "$protected_branch" ]; then
    echo "Pushing to $protected_branch is not allowed."
    exit 1
  fi
done
