name: Add transitive dependencies

on:
    workflow_dispatch:

jobs:
    UpdateDepGraph:
        runs-on: ubuntu-latest
        permissions:
          checks: write
          contents: read
        name: BuildAndTest
        steps: 
              - name: Checkout branch
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
              - name: Maven Dependency Tree Dependency Submission
                uses: advanced-security/maven-dependency-submission-action@v4.0.2
                with:
                    directory: "/"
            
            
