name: Add transitive dependencies

on:
  workflow_dispatch:

jobs:
  UpdateDepGraph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: BuildAndTest
    steps: 
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'

      - name: Maven Dependency Tree Dependency Submission
        uses: advanced-security/maven-dependency-submission-action@v4.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
            
