name: Maven Transitive Dependency Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  generate-and-scan-dependencies:
    runs-on: ubuntu-latest
    permissions:
          security-events: write
          contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'

      - name: Generate Maven Dependency List
        run: mvn dependency:list -DoutputFile=mvn-deps.txt -DappendOutput=true

      - name: Convert Dependency List to JSON
        run: |
          echo '{"results": [{"packages": [' > osv-scanner-deps.json
          cat mvn-deps.txt | grep ":.*:.*:.*:.*" | sed 's/\(.*\):\(.*\):\(.*\):\(.*\)/          {"package": {"name": "\1", "version": "\3", "ecosystem": "maven"}},/g' >> osv-scanner-deps.json
          echo '        ]}]}' >> osv-scanner-deps.json
          
      - name: Upload JSON for OSV Scanner
        uses: actions/upload-artifact@v4
        with:
          name: osv-scanner-deps
          path: osv-scanner-deps.json

      - name: OSV Vulnerability Scanning
        uses: "google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v1.6.2-beta1"
        with:
          download-artifact: osv-scanner-deps
          scan-args: |-
            --lockfile=osv-scanner:osv-scanner-deps.json
