name: Snyk Maven Check
on: [pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 20
        uses: actions/setup-java@v2
        with:
          java-version: '20'
          distribution: 'adopt'
        id: setup-java

      - name: Set executable permissions on mvnw
        run: chmod +x ./mvnw

      - name: Check Maven Dependency Plugin
        run: ./mvnw dependency:tree -DoutputType=dot --batch-mode --non-recursive --file="pom.xml"

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          JAVA_HOME: ${{ steps.setup-java.outputs.java-home }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
